package se.iths.TwoToeSebastian.myservice;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.Id;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

@Data                      // Data for lombok, automatic getters and setters
@Entity                    // This will be an element in autogenerated List
@NoArgsConstructor         // Automatic generation of constructor
public class UserData {

    @Id
    @GeneratedValue int id;       // autogenerate +=1 for each new User
    String userName;
    String realName;
    String city;
    float income;
    boolean inReationship;
}
